export {
  myPhone,
  myEmail,
  myResume,
  currentCity,
  currentCityLink,
  currentCountry,
  currentCountryLink,
  menuData,
  aboutSkillsData,
  socialNetworkData,
  educationData,
  imagesData,
  certificateButtonData,
  skillsCardsData,
  portfolioData,
} from './api';
